// Generated by WebFx

module webfx.demo.medusaclock.application {

    // Direct dependencies modules
    requires javafx.controls;
    requires javafx.graphics;
    requires webfx.lib.medusa;

    // Exported packages
    exports webfx.demo.medusaclock;

    // Provided services
    provides javafx.application.Application with webfx.demo.medusaclock.MedusaClockApplication;

}